<h1 style='text-align: center;font-weight:900;font-size:30px'>NUMPY</h1>

## Aim:

To perform basic array operations using the NumPy library.

## Code :

1. Create a numpy array using a list of ten items.

In [2]:
list_10 = [1,2,3,4,5,6,7,8,9,10]  
#list of ten items
numpy_array = np.array(list_10)      
#created numpy array using list

print('\nOutput:\n')
print('\nNumpy array created using list of ten items is: \n\n',numpy_array,sep='')


Output:


Numpy array created using list of ten items is: 

[ 1  2  3  4  5  6  7  8  9 10]


<div>

2. Create a numpy arrays with different dimensions. <br />
(a) Print the dimensions. <br />
(b) Access the elements from the arrays.

In [4]:
arr_d1 = np.array([1,2,3,4,5,6,7,8])                     
#1-dimensional array
arr_d2 = np.array([[1,2,3,4],[5,6,7,8]])                 
#2-dimensional array
arr_d3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])         
#3-dimensional array

print('\nOutput:\n')
#(a)printing dimensions
print('(a)\nDimension of arr_d1:\n\n',arr_d1,' = ',arr_d1.ndim)
print('\nDimension of arr_d2:\n\n',arr_d2,' = ',arr_d2.ndim)
print('\nDimension of arr_d3:\n\n',arr_d3,' = ',arr_d3.ndim)

#(b)accessing elements
print('\n\n(b)\nElements of arr_d1:\n')
for i in range(len(arr_d1)):
    print('arr_d1[{}]'.format(i),' = ',arr_d1[i])

print('\nElements of arr_d2:\n')
for i in range(len(arr_d2)):
    print('arr_d2[{}]'.format(i),' = ',arr_d2[i])
    
print('\nElements of arr_d3:\n')
for i in range(len(arr_d3)):
    print('arr_d3[{}]'.format(i),' = \n\n',arr_d3[i],end='\n\n')


Output:

(a)
Dimension of arr_d1:

 [1 2 3 4 5 6 7 8]  =  1

Dimension of arr_d2:

 [[1 2 3 4]
 [5 6 7 8]]  =  2

Dimension of arr_d3:

 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]  =  3


(b)
Elements of arr_d1:

arr_d1[0]  =  1
arr_d1[1]  =  2
arr_d1[2]  =  3
arr_d1[3]  =  4
arr_d1[4]  =  5
arr_d1[5]  =  6
arr_d1[6]  =  7
arr_d1[7]  =  8

Elements of arr_d2:

arr_d2[0]  =  [1 2 3 4]
arr_d2[1]  =  [5 6 7 8]

Elements of arr_d3:

arr_d3[0]  = 

 [[1 2]
 [3 4]]

arr_d3[1]  = 

 [[5 6]
 [7 8]]



<div>

3. Perform addition, multiplication and subtraction operations over any
created numpy arrays

In [6]:
arr1 = np.array([1,2,3,4])                 
#array1
arr2 = np.array([2,4,6,8])                 
#array2

print('\nOutput:\n')
print('\nArray 1 = ',arr1)
print('Array 2 = ',arr2)

#addition
print('\n\nArray 1 + Array 2 = ',arr1+arr2)

#multiplication
print('\nArray 1 * Array 2 = ',arr1*arr2)

#subtraction
print('\nArray 1 - Array 2 = ',arr1-arr2)


Output:


Array 1 =  [1 2 3 4]
Array 2 =  [2 4 6 8]


Array 1 + Array 2 =  [ 3  6  9 12]

Array 1 * Array 2 =  [ 2  8 18 32]

Array 1 - Array 2 =  [-1 -2 -3 -4]


<div>

4. Use arrange function in numpy with two examples

<div>

In [8]:
#arange function is used to make arrays of a range of numbers
print('\nOutput:\n')
print('\nExample 1:')
arange_1 = np.arange(0,9)
print('np.arange(0,9) gives: ',arange_1)

print('\nExample 2:')
arange_2 = np.arange(0,9,2)
print('np.arange(0,9,2) gives: ',arange_2)


Output:


Example 1:
np.arange(0,9) gives:  [0 1 2 3 4 5 6 7 8]

Example 2:
np.arange(0,9,2) gives:  [0 2 4 6 8]


<div>

5. Create a numpy array and perform square root and standard deviation on it.

In [9]:
array = np.array([1,4,9,16,25])
print('\nOutput:\n')
print('\nArray = ',array)

#squareroot
print('\nSquare root of the array = ',np.sqrt(array))

#standard deviation
print('\nStandard deviation of the array = ',np.std(array))


Output:


Array =  [ 1  4  9 16 25]

Square root of the array =  [1. 2. 3. 4. 5.]

Standard deviation of the array =  8.648699324175862


<div>

6. Build a 2-dimentional array and perform column sum, row sum, column mean, row mean

In [10]:
arr2d = np.array([[1,2],[3,4]])
print('\nOutput:\n')
print('\nThe 2-dimensional array: ')
for i in arr2d:
    print(i)

#column sum
print('\nColumn sum of the array = ',np.sum(arr2d,axis=0))

#row sum
print('Row sum of the array = ',np.sum(arr2d,axis=1))

#column mean
print('Column mean of the array = ',np.mean(arr2d,axis=0))

#row mean
print('Row mean of the array = ',np.mean(arr2d,axis=1))


Output:


The 2-dimensional array: 
[1 2]
[3 4]

Column sum of the array =  [4 6]
Row sum of the array =  [3 7]
Column mean of the array =  [2. 3.]
Row mean of the array =  [1.5 3.5]


<div>

7. Generate arrays of zeros and ones with shape of (2,4)

In [11]:
#zero array with shape (2,4)
print('\nOutput:\n')
arr_0 = np.zeros((2,4),dtype=int)
print('\nArray of zeroes with shape of (2,4) = \n')
for i in arr_0:
    print(i)
    
#ones array with shape (2,4)
arr_1 = np.ones((2,4),dtype=int)
print('\n\nArray of ones with shape of (2,4) = \n')
for i in arr_1:
    print(i)


Output:


Array of zeroes with shape of (2,4) = 

[0 0 0 0]
[0 0 0 0]


Array of ones with shape of (2,4) = 

[1 1 1 1]
[1 1 1 1]


<div>

8. Create two numpy arrays and append data horizontally and vertically.

In [13]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6],[7,8]])
print('\nOutput:\n')
print('Array 1 = ')
for i in array1:
    print(i)
print('\nArray 2 = ')
for i in array1:
    print(i)

#append data horizontally
horz = np.append(array1,array2,axis=1)
print('\nData appended horizontally: ')
for i in horz:
    print(i)

#append data vertically
vert = np.append(array1,array2,axis=0)
print('\nData appended vertically: ')
for i in vert:
    print(i)


Output:

Array 1 = 
[1 2]
[3 4]

Array 2 = 
[1 2]
[3 4]

Data appended horizontally: 
[1 2 5 6]
[3 4 7 8]

Data appended vertically: 
[1 2]
[3 4]
[5 6]
[7 8]


<div>

9. Build two numpy array and perform the following operations

In [15]:
arrI = np.array([8,3,6,9,5,3,6,2,1,0])
arrII = np.array([1,7,9,4,8,4,7,4,0,3])
print('\nOutput:\n')
print('\nArray 1 = ',arrI)
print('Array 2 = ',arrII)

#(i)search
qry = int(input('\n(i) Enter element to search for: '))
srch1 = np.where(arrI==qry)
srch2 = np.where(arrII==qry)

#searching array 1
if srch1[0].size > 0 :
    print('\nElement found in array 1 at index(es): ',end='')
    for i in srch1[0]:
        print([i],end=' ')
else:
    print('\nElement not found in array 1.')
    
#searching array 2
if srch2[0].size > 0 :
    print('\nElement found in array 2 at index(es): ',end='')
    for i in srch2[0]:
        print([i],end=' ')
else:
    print('\nElement not found in array 2.')
    
#(ii)Join
print('\n\n(ii) The joined array is: ',np.concatenate((arrI,arrII)))

#(iii)Sort
print('\n\n(iii) The sorted array 1 is: ',np.sort(arrI))
print('      The sorted array 2 is: ',np.sort(arrII))

#(iv)Broadcast
val = 10
print('\n\n(iv) Broadcast result for array 1: ',arrI+val)
print('     Broadcast result for array 2: ',arrII+val)


Output:


Array 1 =  [8 3 6 9 5 3 6 2 1 0]
Array 2 =  [1 7 9 4 8 4 7 4 0 3]

(i) Enter element to search for: 5

Element found in array 1 at index(es): [4] 
Element not found in array 2.


(ii) The joined array is:  [8 3 6 9 5 3 6 2 1 0 1 7 9 4 8 4 7 4 0 3]


(iii) The sorted array 1 is:  [0 1 2 3 3 5 6 6 8 9]
      The sorted array 2 is:  [0 1 3 4 4 4 7 7 8 9]


(iv) Broadcast result for array 1:  [18 13 16 19 15 13 16 12 11 10]
     Broadcast result for array 2:  [11 17 19 14 18 14 17 14 10 13]


<div>

10. Generate the following <br />
(a) One dimensional array with 5 random integers from 10 to 50 <br />
(b) Two-dimensional array with 4 rows, each row containing 3 random integers

In [2]:
import numpy as np
#1d array with 5 random integers from 10 to 50
print('\nOutput:\n')
rand_1d = np.random.randint(10,51,size=5)
print('\n(a) 1 dimensional array:',rand_1d)

#2d array with with 4 rows, each row containing 3 random integers from 5 to 10
rand_2d = np.random.randint(5,11,size=(4,3))
print('\n(b) Two-dimensional array:\n')
for i in rand_2d:
    print(i)


Output:


(a) 1 dimensional array: [32 13 34 30 15]

(b) Two-dimensional array:

[5 6 7]
[ 8 10  5]
[ 6 10  9]
[8 6 6]


<div>

11. Reverse a vector such that first element becomes last

In [17]:
vector = np.random.randint(0,10,size=10)
print('\nOutput:\n')
print('\nVector = ',vector)

#reverse vector
rev_vector = np.flip(vector)
print('\nReversed Vector = ',rev_vector)


Output:


Vector =  [4 3 2 8 5 3 7 2 6 5]

Reversed Vector =  [5 6 2 7 3 5 8 2 3 4]


<div>

12. Create a 3x3 matrix with values ranging from 0 to 8

In [23]:
#3x3 matrix
matrix_values = np.arange(0,9)
matrix = matrix_values.reshape((3,3))
print('\nOutput:\n')
print('A 3x3 matrix with values ranging from 0 to 8:\n')
for i in matrix:
    print(i)


Output:

A 3x3 matrix with values ranging from 0 to 8:

[0 1 2]
[3 4 5]
[6 7 8]


<div>

13. Create a 3x3x3 array with random values

In [21]:
#3x3x3 matrix
arr_333 = np.random.randint(np.random.randint(50), size = (3,3,3))
print('\nOutput:\n')
print('\nA 3x3x3 array with random values: \n\n',arr_333)


Output:


A 3x3x3 array with random values: 

 [[[1 1 1]
  [1 0 1]
  [0 1 0]]

 [[0 0 1]
  [0 0 0]
  [1 0 0]]

 [[1 1 1]
  [0 1 0]
  [1 1 1]]]


<div>

14. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
#10x10 array
arr_10x10 = np.random.randint(np.random.randint(35), size = (10,10))
print('\nOutput:\n')
print(' A 10x10 array with random values: \n\n',arr_10x10)

#minimum value
print('\nMinimum value of the array = ',arr_10x10.min())

#maximum value
print('\nMaximum value of the array = ',arr_10x10.max())


Output:

 A 10x10 array with random values: 

 [[18 13 32 23 11  3 19 31 14  1]
 [30  5 31 22 16 32  9  4  8  4]
 [24 13  5 10 16  9 27  4 24 13]
 [27  2 25 21 24 28 21 16 12  9]
 [11 28  8 28 23 31 29 23 28  7]
 [ 6  1 18 29  4 22 20 11 31 14]
 [14 24  5 28 19 10 32 22 26 16]
 [30 30 16 10  5 28 21 26 10 29]
 [32 23 26 31 10  8 20 25 15  0]
 [25  7  1 23  1 24 31  9 11 21]]

Minimum value of the array =  0

Maximum value of the array =  32


<div>

15. Compute ((A+B)*(-A/2)) for array in 1D and 2D

In [33]:
#1D
A_1d = np.random.randint(1,50,size = 10)
B_1d = np.random.randint(1,50,size = 10)
print('\nOutput:\n')
print('1D:\n   A = ',A_1d,'\n   B = ',B_1d)

#((A+B)*(-A/2)) for array in 1D
print('\n   (A+B)*(-A/2) = ',((A_1d+B_1d)*(-A_1d/2)))

#2D
A_2d = np.random.randint(1,50,size = (3,3))
B_2d = np.random.randint(1,50,size = (3,3))
print('\n2D:\n   A = \n',A_2d,'\n   B = \n',B_2d)

#((A+B)*(-A/2)) for array in 2D
print('\n\n(A+B)*(-A/2) = \n',((A_2d+B_2d)*(-A_2d/2)))


Output:

1D:
   A =  [15 43 11 48 27 46  2 46 40 47] 
   B =  [ 1 14 25 46 21  6 41  8 12  8]

   (A+B)*(-A/2) =  [ -120.  -1225.5  -198.  -2256.   -648.  -1196.    -43.  -1242.  -1040.
 -1292.5]

2D:
   A = 
 [[19  8 41]
 [ 8 15 16]
 [38 14 16]] 
   B = 
 [[26 47 25]
 [46 26 11]
 [25 16 49]]


(A+B)*(-A/2) = 
 [[ -427.5  -220.  -1353. ]
 [ -216.   -307.5  -216. ]
 [-1197.   -210.   -520. ]]


<div>

16. Create random vector of size 10 and replace the maximum value by 0

In [35]:
vect = np.random.randint(-10,10, size = 10)
print('\nOutput:\n')
print('Vector of size 10 = ',vect)

#replacing max value by 0
vect[vect.argmax()] = 0
print('\nAfter replacing maximum value by zero: ',vect)


Output:

Vector of size 10 =  [-10  -1  -6   6   0   3   8  -7   1   3]

After replacing maximum value by zero:  [-10  -1  -6   6   0   3   0  -7   1   3]


<div>

17. Replace items that satisfy a condition with another value in numpy array. <br />
Condition: Replace all odd numbers in arr with -1
Input:<br/>
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])<br/>
Output:<br/>
array([ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1])

In [37]:
#input values to a list
vals = []
print('\nOutput:\n')
elems = int(input('Enter the number of elements in the array: '))
for i in range(elems):
    vals.append(int(input('Enter value {}: '.format(i+1))))

#convert list to array
Array = np.array(vals)
print('\nArray = ',Array)

#replace odd numbers with -1
for j in range(len(Array)):
    if Array[j]%2 == 1:
        Array[j] = -1
print('\nAfter replacing all odd numbers with -1 = ',Array)


Output:

Enter the number of elements in the array: 4
Enter value 1: 2
Enter value 2: 5
Enter value 3: 2
Enter value 4: 8

Array =  [2 5 2 8]

After replacing all odd numbers with -1 =  [ 2 -1  2  8]


<div>